{% set name = "dynorrt" %}
{% set version = "0.0.12" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/quimortiz/dynorrt.git
  git_rev: 75a875bee55f3945d230360c0cfb276f0b6e994a

#
# maybe i can put this into package!
#
build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - python {{python}}                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
  host:
    - python {{python}}
    - pinocchio >=2.7.0
    - numpy

  run:
    - python {{python}}
    - {{ pin_compatible('numpy') }}
    - pinocchio >=2.7.0

test:
  commands:
    - python -c "import pydynorrt"  # Adjust to your package's import test


about:
  home: https://github.com/quimortiz/dynorrt
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Fast and flexible and easy-to-use implementation of RRT and variants.
  description: |
    Fast and flexible and easy-to-use implementation of RRT and variants.
  doc_url: https://github.com/quimortiz/dynorrt
  dev_url: https://github.com/quimortiz/dynorrt


extra:
  recipe-maintainers:
    - quimortiz
